// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PmTracker.Web.Data;

#nullable disable

namespace PmTracker.Web.Migrations
{
    [DbContext(typeof(PmTrackerDbContext))]
    [Migration("20260420154159_VyzvyFaze1")]
    partial class VyzvyFaze1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PmTracker.Web.Models.Entities.AuthzAuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<int?>("ActorOsobaId")
                        .HasColumnType("int")
                        .HasColumnName("actor_osoba_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.HasKey("Id");

                    b.ToTable("audit_log", "authz");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.AuthzPermissionCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("permission_categories", "authz");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.AuthzPermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Klic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("klic");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.Property<string>("ScopeLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scope_level");

                    b.HasKey("Id");

                    b.ToTable("permissions", "authz");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.AuthzRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.Property<string>("Popis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("popis");

                    b.HasKey("Id");

                    b.ToTable("roles", "authz");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.AuthzRolePermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit")
                        .HasColumnName("is_allowed");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("ScopeMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("scope_mode");

                    b.HasKey("Id");

                    b.ToTable("role_permissions", "authz");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.AuthzRolePermissionProjectEntity", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .HasColumnType("int")
                        .HasColumnName("role_permission_id");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int")
                        .HasColumnName("projekt_id");

                    b.HasKey("RolePermissionId", "ProjektId");

                    b.ToTable("role_permission_projects", "authz");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.AuthzSuperadminEntity", b =>
                {
                    b.Property<int>("OsobaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("osoba_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OsobaId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Poznamka")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("poznamka");

                    b.HasKey("OsobaId");

                    b.ToTable("superadmins", "authz");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.AuthzUserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("OsobaId")
                        .HasColumnType("int")
                        .HasColumnName("osoba_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.ToTable("user_roles", "authz");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikKategoriiZaznamuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_kategorii_zaznamu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikOrganizaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_organizace", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikOrganizacniCelekEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_organizacni_celky", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikRoleSubsystemuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_roli_subsystemu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikRoliProjektuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_roli_projektu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikStavuJednaniEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_stavu_jednani", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikStavuProjektuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_stavu_projektu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikStavuUcastiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_stavu_ucasti", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikStavuUkoluEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit")
                        .HasColumnName("is_final");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_stavu_ukolu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikTypuExternichOdkazuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_typu_externich_odkazu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikTypuUkoluEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("ciselnik_typu_ukolu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.HarmonogramSablonaEntity", b =>
                {
                    b.Property<int>("Verze")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("verze");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Verze"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("DelayBarvaHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delay_barva_hex");

                    b.Property<bool>("IsAktivni")
                        .HasColumnType("bit")
                        .HasColumnName("is_aktivni");

                    b.HasKey("Verze");

                    b.HasIndex("IsAktivni")
                        .IsUnique()
                        .HasDatabaseName("UQ_harmonogram_sablony_aktivni")
                        .HasFilter("[is_aktivni] = 1");

                    b.ToTable("harmonogram_sablony", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.HarmonogramTypEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarvaHex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("barva_hex");

                    b.Property<int>("Hodnota")
                        .HasColumnType("int")
                        .HasColumnName("hodnota");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<bool>("JeZpozdeni")
                        .HasColumnType("bit")
                        .HasColumnName("je_zpozdeni");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("kod");

                    b.Property<Guid>("KrokKey")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("krok_key");

                    b.Property<int>("KrokPoradi")
                        .HasColumnType("int")
                        .HasColumnName("krok_poradi");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.Property<int>("SablonaVerze")
                        .HasColumnType("int")
                        .HasColumnName("sablona_verze");

                    b.HasKey("Id");

                    b.HasIndex("SablonaVerze", "Kod")
                        .IsUnique()
                        .HasDatabaseName("UQ_ciselnik_harmonogram_typu_sablona_kod");

                    b.HasIndex("SablonaVerze", "KrokPoradi", "JeZpozdeni")
                        .IsUnique()
                        .HasDatabaseName("UQ_ciselnik_harmonogram_typu_sablona_krok_zpozdeni");

                    b.ToTable("ciselnik_harmonogram_typu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.JednaniEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CasZacatek")
                        .HasColumnType("time(0)")
                        .HasColumnName("cas_zacatek");

                    b.Property<int>("CisloJednani")
                        .HasColumnType("int")
                        .HasColumnName("cislo_jednani");

                    b.Property<DateTime>("DatumPlanovane")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_planovane");

                    b.Property<string>("Misto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("misto");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int")
                        .HasColumnName("projekt_id");

                    b.Property<int>("StavJednaniId")
                        .HasColumnType("int")
                        .HasColumnName("stav_jednani_id");

                    b.Property<int?>("UzamklOsobaId")
                        .HasColumnType("int")
                        .HasColumnName("uzamkl_osoba_id");

                    b.HasKey("Id");

                    b.ToTable("jednani", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ObsazeniProjektuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumOdebrani")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_odebrani");

                    b.Property<DateTime>("DatumPrirazeni")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_prirazeni");

                    b.Property<int>("OsobaId")
                        .HasColumnType("int")
                        .HasColumnName("osoba_id");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int")
                        .HasColumnName("projekt_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId", "OsobaId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_obsazeni_projektu_projekt_osoba_role_aktivni")
                        .HasFilter("[datum_odebrani] IS NULL");

                    b.ToTable("obsazeni_projektu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ObsazeniSubsystemuProjektuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumOdebrani")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_odebrani");

                    b.Property<DateTime>("DatumPrirazeni")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_prirazeni");

                    b.Property<int>("OsobaId")
                        .HasColumnType("int")
                        .HasColumnName("osoba_id");

                    b.Property<int>("ProjektSubsystemId")
                        .HasColumnType("int")
                        .HasColumnName("projekt_subsystem_id");

                    b.Property<int>("RoleSubsystemuId")
                        .HasColumnType("int")
                        .HasColumnName("role_subsystemu_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjektSubsystemId", "OsobaId", "RoleSubsystemuId")
                        .IsUnique()
                        .HasDatabaseName("UX_obsazeni_subsystemu_projektu_aktivni")
                        .HasFilter("[datum_odebrani] IS NULL");

                    b.ToTable("obsazeni_subsystemu_projektu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.OsobaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdLogin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ad_login");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<Guid?>("GuidAd")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Guid_AD");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jmeno");

                    b.Property<bool>("LocationLocked")
                        .HasColumnType("bit")
                        .HasColumnName("location_locked");

                    b.Property<int>("OrganizaceId")
                        .HasColumnType("int")
                        .HasColumnName("organizace_id");

                    b.Property<int?>("OrganizacniCelekId")
                        .HasColumnType("int")
                        .HasColumnName("organizacni_celek_id");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prijmeni");

                    b.Property<string>("Titul")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titul");

                    b.HasKey("Id");

                    b.ToTable("osoby", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ProjektEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CelyNazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cely_nazev");

                    b.Property<string>("CisloRamcoveSmlouvy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cislo_ramcove_smlouvy");

                    b.Property<string>("MistoPlneni")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("misto_plneni");

                    b.Property<bool>("PouzivatIdentJednani")
                        .HasColumnType("bit")
                        .HasColumnName("pouzivat_ident_jednani");

                    b.Property<int>("StavId")
                        .HasColumnType("int")
                        .HasColumnName("stav_id");

                    b.Property<string>("Zkratka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zkratka");

                    b.HasKey("Id");

                    b.HasIndex("StavId");

                    b.ToTable("projekty", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ProjektSubsystemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumOdebrani")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_odebrani");

                    b.Property<DateTime>("DatumPrirazeni")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_prirazeni");

                    b.Property<int>("Poradi")
                        .HasColumnType("int")
                        .HasColumnName("poradi");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int")
                        .HasColumnName("projekt_id");

                    b.Property<int>("SubsystemId")
                        .HasColumnType("int")
                        .HasColumnName("subsystem_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId", "Poradi")
                        .IsUnique()
                        .HasDatabaseName("UX_projekt_subsystemy_projekt_poradi_aktivni")
                        .HasFilter("[datum_odebrani] IS NULL");

                    b.HasIndex("ProjektId", "SubsystemId")
                        .IsUnique()
                        .HasDatabaseName("UX_projekt_subsystemy_projekt_subsystem_aktivni")
                        .HasFilter("[datum_odebrani] IS NULL");

                    b.ToTable("projekt_subsystemy", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ProjektovyZaznamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AktualniTypUkoluId")
                        .HasColumnType("int")
                        .HasColumnName("aktualni_typ_ukolu_id");

                    b.Property<string>("Cil")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cil");

                    b.Property<int?>("CisloJednaniZdrojId")
                        .HasColumnType("int")
                        .HasColumnName("cislo_jednani_zdroj_id");

                    b.Property<string>("CisloViditelne")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("cislo_viditelne");

                    b.Property<int>("CisloViditelneA")
                        .HasColumnType("int")
                        .HasColumnName("cislo_viditelne_a");

                    b.Property<int>("CisloViditelneB")
                        .HasColumnType("int")
                        .HasColumnName("cislo_viditelne_b");

                    b.Property<byte>("CisloViditelneTyp")
                        .HasColumnType("tinyint")
                        .HasColumnName("cislo_viditelne_typ");

                    b.Property<int>("CisloZaznamu")
                        .HasColumnType("int")
                        .HasColumnName("cislo_zaznamu");

                    b.Property<DateTime>("DatumUkonceni")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_ukonceni");

                    b.Property<DateTime>("DatumZalozeni")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zalozeni");

                    b.Property<int>("HarmonogramSablonaVerze")
                        .HasColumnType("int")
                        .HasColumnName("harmonogram_sablona_verze");

                    b.Property<int>("KategorieId")
                        .HasColumnType("int")
                        .HasColumnName("kategorie_id");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.Property<string>("Popis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("popis");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int")
                        .HasColumnName("projekt_id");

                    b.Property<int?>("StavUkoluId")
                        .HasColumnType("int")
                        .HasColumnName("stav_ukolu_id");

                    b.Property<int>("SubsystemId")
                        .HasColumnType("int")
                        .HasColumnName("subsystem_id");

                    b.Property<int>("VlastnikId")
                        .HasColumnType("int")
                        .HasColumnName("vlastnik_id");

                    b.HasKey("Id");

                    b.HasIndex("CisloJednaniZdrojId");

                    b.HasIndex("HarmonogramSablonaVerze");

                    b.HasIndex("ProjektId", "CisloViditelne")
                        .IsUnique()
                        .HasDatabaseName("UX_projektove_zaznamy_projekt_cislo_viditelne")
                        .HasFilter("[cislo_viditelne] IS NOT NULL");

                    b.HasIndex("ProjektId", "CisloViditelneA", "CisloViditelneB")
                        .IsUnique()
                        .HasDatabaseName("UX_projektove_zaznamy_projekt_meeting_order")
                        .HasFilter("[cislo_viditelne_typ] = 1");

                    b.HasIndex("ProjektId", "CisloViditelneA", "CisloViditelneB", "CisloZaznamu")
                        .HasDatabaseName("IX_projektove_zaznamy_projekt_sort");

                    b.ToTable("projektove_zaznamy", null, t =>
                        {
                            t.HasCheckConstraint("CK_projektove_zaznamy_cislo_viditelne_consistency", "((cislo_viditelne_typ = 0 AND cislo_jednani_zdroj_id IS NULL AND cislo_viditelne_b = 0) OR (cislo_viditelne_typ = 1 AND cislo_jednani_zdroj_id IS NOT NULL AND cislo_viditelne_b > 0))");

                            t.HasCheckConstraint("CK_projektove_zaznamy_cislo_viditelne_typ", "cislo_viditelne_typ IN (0, 1)");
                        });
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.SearchReindexCheckpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_processed_at");

                    b.Property<long>("LastProcessedAuditId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_processed_audit_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("search_reindex_checkpoint", "dbo");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.SubsystemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kód");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazev");

                    b.HasKey("Id");

                    b.ToTable("subsystemy", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.UcastEntity", b =>
                {
                    b.Property<int>("JednaniId")
                        .HasColumnType("int")
                        .HasColumnName("jednani_id");

                    b.Property<int>("OsobaId")
                        .HasColumnType("int")
                        .HasColumnName("osoba_id");

                    b.Property<int>("StavUcastiId")
                        .HasColumnType("int")
                        .HasColumnName("stav_ucasti_id");

                    b.HasKey("JednaniId", "OsobaId");

                    b.ToTable("ucast", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.VyjadreniEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorOsobaId")
                        .HasColumnType("int")
                        .HasColumnName("autor_osoba_id");

                    b.Property<DateTime>("DatumVyjadreni")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_vyjadreni");

                    b.Property<int>("JednaniId")
                        .HasColumnType("int")
                        .HasColumnName("jednani_id");

                    b.Property<string>("TextVyjadreni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text_vyjadreni");

                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.HasKey("Id");

                    b.ToTable("vyjadreni", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.VyzvaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CisloRamcoveSmlouvySnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cislo_ramcove_smlouvy_snapshot");

                    b.Property<DateTime?>("DatumOdeslani")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_odeslani");

                    b.Property<DateTime>("DatumZalozeni")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zalozeni");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("kod");

                    b.Property<string>("MistoPlneniSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("misto_plneni_snapshot");

                    b.Property<int?>("OdeslalOsobaId")
                        .HasColumnType("int")
                        .HasColumnName("odeslal_osoba_id");

                    b.Property<int>("PoradoveVRoce")
                        .HasColumnType("int")
                        .HasColumnName("poradove_v_roce");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int")
                        .HasColumnName("projekt_id");

                    b.Property<int>("Rok")
                        .HasColumnType("int")
                        .HasColumnName("rok");

                    b.Property<byte>("Stav")
                        .HasColumnType("tinyint")
                        .HasColumnName("stav");

                    b.Property<int>("ZalozilOsobaId")
                        .HasColumnType("int")
                        .HasColumnName("zalozil_osoba_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId", "DatumZalozeni")
                        .HasDatabaseName("ix_vyzvy_projekt_datum_desc");

                    b.HasIndex("CisloRamcoveSmlouvySnapshot", "Rok", "PoradoveVRoce")
                        .IsUnique()
                        .HasDatabaseName("ux_vyzvy_smlouva_rok_poradove");

                    b.ToTable("vyzvy", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.VyzvaHistorieStavuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZmeny")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zmeny");

                    b.Property<byte>("NovyStav")
                        .HasColumnType("tinyint")
                        .HasColumnName("novy_stav");

                    b.Property<byte?>("PuvodniStav")
                        .HasColumnType("tinyint")
                        .HasColumnName("puvodni_stav");

                    b.Property<int>("VyzvaId")
                        .HasColumnType("int")
                        .HasColumnName("vyzva_id");

                    b.Property<int>("ZmenilOsobaId")
                        .HasColumnType("int")
                        .HasColumnName("zmenil_osoba_id");

                    b.HasKey("Id");

                    b.HasIndex("VyzvaId")
                        .HasDatabaseName("ix_vyzva_historie_stavu_vyzva_id");

                    b.ToTable("vyzva_historie_stavu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamExterniOdkazEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cislo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("cislo");

                    b.Property<DateTime?>("DatumDodani")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_dodani");

                    b.Property<DateTime?>("DatumObjednani")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_objednani");

                    b.Property<DateTime?>("DatumPrevzeti")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_prevzeti");

                    b.Property<DateTime?>("PlanDodani")
                        .HasColumnType("datetime2")
                        .HasColumnName("plan_dodani");

                    b.Property<decimal?>("PredpokladanaCena")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("predpokladana_cena");

                    b.Property<int>("TypOdkazuId")
                        .HasColumnType("int")
                        .HasColumnName("typ_odkazu_id");

                    b.Property<int?>("VyzvaId")
                        .HasColumnType("int")
                        .HasColumnName("vyzva_id");

                    b.Property<bool>("ZaradidDoVyzvy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("zaradid_do_vyzvy");

                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.HasKey("Id");

                    b.HasIndex("Cislo")
                        .IsUnique()
                        .HasDatabaseName("ux_zaznam_externi_odkazy_cislo_in_vyzve")
                        .HasFilter("[vyzva_id] IS NOT NULL");

                    b.HasIndex("VyzvaId");

                    b.ToTable("zaznam_externi_odkazy", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamHarmonogramHodnotaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HodnotaInt")
                        .HasColumnType("int")
                        .HasColumnName("hodnota_int");

                    b.Property<int>("TypId")
                        .HasColumnType("int")
                        .HasColumnName("typ_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.HasKey("Id");

                    b.HasIndex("ZaznamId", "TypId")
                        .IsUnique()
                        .HasDatabaseName("UQ_zaznam_harmonogram_hodnoty_zaznam_typ");

                    b.ToTable("zaznam_harmonogram_hodnoty", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamHistorieStavuProjektuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZmeny")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zmeny");

                    b.Property<int>("NovyStav")
                        .HasColumnType("int")
                        .HasColumnName("novy_stav");

                    b.Property<int>("PuvodniStav")
                        .HasColumnType("int")
                        .HasColumnName("puvodni_stav");

                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.HasKey("Id");

                    b.ToTable("zaznam_historie_stavu_projektu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamHistorieStavuZaznamuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZmeny")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zmeny");

                    b.Property<int>("NovyStav")
                        .HasColumnType("int")
                        .HasColumnName("novy_stav");

                    b.Property<int>("PuvodniStav")
                        .HasColumnType("int")
                        .HasColumnName("puvodni_stav");

                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.HasKey("Id");

                    b.ToTable("zaznam_historie_stavu_zaznamu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamHistorieSubsystemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZmeny")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zmeny");

                    b.Property<int>("NovySubsystem")
                        .HasColumnType("int")
                        .HasColumnName("novy_subsystem");

                    b.Property<int>("PuvodniSubsystem")
                        .HasColumnType("int")
                        .HasColumnName("puvodni_subsystem");

                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.HasKey("Id");

                    b.ToTable("zaznam_historie_subsystem", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamHistorieTerminuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZmeny")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zmeny");

                    b.Property<string>("Duvod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duvod");

                    b.Property<DateTime>("NoveDatum")
                        .HasColumnType("datetime2")
                        .HasColumnName("nove_datum");

                    b.Property<DateTime>("PuvodniDatum")
                        .HasColumnType("datetime2")
                        .HasColumnName("puvodni_datum");

                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.HasKey("Id");

                    b.ToTable("zaznam_historie_terminu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamHistorieVlastnikEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZmeny")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zmeny");

                    b.Property<int>("NovyVlastnik")
                        .HasColumnType("int")
                        .HasColumnName("novy_vlastnik");

                    b.Property<int>("PuvodniVlastnik")
                        .HasColumnType("int")
                        .HasColumnName("puvodni_vlastnik");

                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.HasKey("Id");

                    b.ToTable("zaznam_historie_vlastnik", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamHistorieZmenTypuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumZmeny")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_zmeny");

                    b.Property<int>("NovyTypId")
                        .HasColumnType("int")
                        .HasColumnName("novy_typ_id");

                    b.Property<int>("PuvodniTypId")
                        .HasColumnType("int")
                        .HasColumnName("puvodni_typ_id");

                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.Property<int>("ZmenilOsobaId")
                        .HasColumnType("int")
                        .HasColumnName("zmenil_osoba_id");

                    b.HasKey("Id");

                    b.ToTable("zaznam_historie_zmen_typu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamNavrhEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedRecordId")
                        .HasColumnType("int")
                        .HasColumnName("approved_record_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByOsobaId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_osoba_id");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("decided_at");

                    b.Property<int?>("DecidedByOsobaId")
                        .HasColumnType("int")
                        .HasColumnName("decided_by_osoba_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int")
                        .HasColumnName("projekt_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Stav")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("stav");

                    b.Property<int>("SubsystemId")
                        .HasColumnType("int")
                        .HasColumnName("subsystem_id");

                    b.Property<string>("TypNavrhu")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("typ_navrhu");

                    b.Property<int?>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId", "CreatedAt")
                        .HasDatabaseName("IX_zaznam_navrhy_projekt_created_at");

                    b.HasIndex("ZaznamId", "TypNavrhu")
                        .IsUnique()
                        .HasDatabaseName("UX_zaznam_navrhy_pending_schedule_per_record")
                        .HasFilter("[stav] = 'PENDING' AND [typ_navrhu] = 'SCHEDULE_PLAN_CHANGE'");

                    b.HasIndex("ZaznamId", "TypNavrhu", "Stav")
                        .HasDatabaseName("IX_zaznam_navrhy_zaznam_typ_stav");

                    b.ToTable("zaznam_navrhy", null, t =>
                        {
                            t.HasCheckConstraint("CK_zaznam_navrhy_stav", "stav IN ('PENDING', 'APPROVED', 'REJECTED')");

                            t.HasCheckConstraint("CK_zaznam_navrhy_typ", "typ_navrhu IN ('CREATE_RECORD', 'SCHEDULE_PLAN_CHANGE')");
                        });
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamPriorityRebuildStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastFullRebuildAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_full_rebuild_at");

                    b.Property<long?>("LastFullRebuildDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("last_full_rebuild_duration_ms");

                    b.Property<string>("LastFullRebuildStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("last_full_rebuild_status");

                    b.Property<int?>("LastFullRebuildTaskCount")
                        .HasColumnType("int")
                        .HasColumnName("last_full_rebuild_task_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("zaznam_priority_rebuild_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_zaznam_priority_rebuild_state_singleton", "id = 1");

                            t.HasCheckConstraint("CK_zaznam_priority_rebuild_state_status", "last_full_rebuild_status IN ('NEVER', 'SUCCESS', 'FAILED', 'RUNNING')");
                        });
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamPriorityUzivateleEntity", b =>
                {
                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.Property<int>("OsobaId")
                        .HasColumnType("int")
                        .HasColumnName("osoba_id");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("computed_at");

                    b.Property<int>("DeadlineSignal")
                        .HasColumnType("int")
                        .HasColumnName("deadline_signal");

                    b.Property<int>("MilestoneSignal")
                        .HasColumnType("int")
                        .HasColumnName("milestone_signal");

                    b.Property<int>("RoleWeight")
                        .HasColumnType("int")
                        .HasColumnName("role_weight");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.HasKey("ZaznamId", "OsobaId");

                    b.HasIndex("OsobaId", "Score", "ZaznamId")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("IX_zaznam_priority_uzivatelu_osoba_score_zaznam");

                    b.ToTable("zaznam_priority_uzivatelu", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamSpolupraceEntity", b =>
                {
                    b.Property<int>("ZaznamId")
                        .HasColumnType("int")
                        .HasColumnName("zaznam_id");

                    b.Property<int>("OsobaId")
                        .HasColumnType("int")
                        .HasColumnName("osoba_id");

                    b.HasKey("ZaznamId", "OsobaId");

                    b.ToTable("zaznam_spoluprace", (string)null);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.HarmonogramTypEntity", b =>
                {
                    b.HasOne("PmTracker.Web.Models.Entities.HarmonogramSablonaEntity", null)
                        .WithMany()
                        .HasForeignKey("SablonaVerze")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ciselnik_harmonogram_typu_sablona");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ProjektEntity", b =>
                {
                    b.HasOne("PmTracker.Web.Models.Entities.CiselnikStavuProjektuEntity", null)
                        .WithMany("Projekty")
                        .HasForeignKey("StavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ProjektovyZaznamEntity", b =>
                {
                    b.HasOne("PmTracker.Web.Models.Entities.JednaniEntity", null)
                        .WithMany()
                        .HasForeignKey("CisloJednaniZdrojId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_projektove_zaznamy_cislo_jednani_zdroj");

                    b.HasOne("PmTracker.Web.Models.Entities.HarmonogramSablonaEntity", null)
                        .WithMany()
                        .HasForeignKey("HarmonogramSablonaVerze")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_projektove_zaznamy_harmonogram_sablona");
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.VyzvaEntity", b =>
                {
                    b.HasOne("PmTracker.Web.Models.Entities.ProjektEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.VyzvaHistorieStavuEntity", b =>
                {
                    b.HasOne("PmTracker.Web.Models.Entities.VyzvaEntity", null)
                        .WithMany()
                        .HasForeignKey("VyzvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.ZaznamExterniOdkazEntity", b =>
                {
                    b.HasOne("PmTracker.Web.Models.Entities.VyzvaEntity", null)
                        .WithMany()
                        .HasForeignKey("VyzvaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PmTracker.Web.Models.Entities.CiselnikStavuProjektuEntity", b =>
                {
                    b.Navigation("Projekty");
                });
#pragma warning restore 612, 618
        }
    }
}
